### ISSUE TITLE
[Feature Request]: Tag 1.21 version as 1.21.1 on Curseforge

### ISSUE THREAD

**Issue by BugmanBugman** [Team-Resourceful/Resouceful-Config#25]
### Is your feature request related to a problem?

Some mods are on 1.21.1 already and they need this mod to work, but you cant dwonload it on launchers like prism.

### Mod Version

1.21.1

### Mod Loader Version

1.21.1

### Mod Loader

N/A

**Comment by ThatGravyBoat** [comment]
Done

**Comment by costentz** [comment]
The same issue is present on Modrinth, can it also be done there?

**Comment by Xplodin** [comment]
curseforge still shows that the mod is NOT available for 1.21.1
past 3.0.4
Mods are requiring this to be 3.0.7 or higher, yet CF, prism, and others dont see 1.21 and 1.21.1 as the same
